### ISSUE TITLE
Unable to use standardx anymore

### ISSUE THREAD

**Issue by bduff9** [aMarCruz/eslint-plugin-prettierx#7]
Hello!  Love prettierx, been using it for a couple years.  I don't know when exactly, but recently, my linting started failing with an error on an invalid prettierx/options config (Error below).  If I comment out the standardx extends, it seems to run successfully, but unsure what that really means in terms of not having a base config to extend.

Error:
```
❯ npm run lint 

> nfl-pool-be@0.0.3 lint /Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-be
> eslint src/ --ext .js,.ts


Oops! Something went wrong! :(

ESLint: 7.19.0

Error: .eslintrc.js » plugin:prettierx/standardx:
        Configuration for rule "prettierx/options" is invalid:
        Value {"alignObjectProperties":false,"alignTernaryLines":false,"arrowParens":"avoid","bracketSpacing":true,"breakBeforeElse":false,"endOfLine":"lf","generatorStarSpacing":true,"htmlWhitespaceSensitivity":"css","indentChains":true,"insertPragma":false,"jsxBracketSameLine":false,"jsxSingleQuote":true,"parenSpacing":false,"printWidth":80,"proseWrap":"preserve","quoteProps":"as-needed","requirePragma":false,"semi":false,"singleQuote":true,"spaceBeforeFunctionParen":true,"tabWidth":2,"trailingComma":"none","useTabs":false,"yieldStarSpacing":true} should NOT have additional properties.

    at ConfigValidator.validateRuleOptions (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-be/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:142:23)
    at /Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-be/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:197:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-be/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:194:34)
    at ConfigValidator.validateConfigArray (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-be/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:320:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-be/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-be/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:21)
    at FileEnumerator._iterateFilesRecursive (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-be/node_modules/eslint/lib/cli-engine/file-enumerator.js:476:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/bduffey2/projects/nfl-pool-serverless/nfl-pool-be/node_modules/eslint/lib/cli-engine/file-enumerator.js:296:49)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nfl-pool-be@0.0.3 lint: `eslint src/ --ext .js,.ts`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the nfl-pool-be@0.0.3 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bduffey2/.npm/_logs/2021-02-02T01_28_51_650Z-debug.log
```

My .eslintrc.js file:
```
module.exports = {
	root: true,
	env: {
		es2021: true,
		jest: true,
		node: true,
	},
	parser: '@typescript-eslint/parser',
	parserOptions: {
		ecmaFeatures: {
			experimentalObjectRestSpread: true,
		},
		warnOnUnsupportedTypeScriptVersion: false,
		ecmaVersion: 7,
		project: './tsconfig.json',
		sourceType: 'module',
	},
	plugins: ['graphql', 'import', 'prettierx', '@typescript-eslint'],
	settings: {
		prettierx: {
			usePrettierrc: false,
		},
	},
	extends: [
		'eslint:recommended',
		'plugin:@typescript-eslint/recommended',
		'plugin:import/errors',
		'plugin:import/typescript',
		'plugin:import/warnings',
		'plugin:prettierx/standardx',
		'plugin:prettierx/@typescript-eslint',
		'plugin:you-dont-need-momentjs/recommended',
	],
	rules: {
		'prettierx/options': [
			2,
			{
				alignObjectProperties: false,
				semi: true,
				singleQuote: true,
				spaceBeforeFunctionParen: true,
				trailingComma: 'all',
				useTabs: true,
			},
		],
		'linebreak-style': 'off',
		'no-console': 'off',
		'no-constant-condition': 'off',
		'no-unused-vars': [
			'warn',
			{
				varsIgnorePattern: 'UU',
				args: 'none',
			},
		],
		quotes: 'off',
		'import/named': 2,
		'import/order': [
			'error',
			{
				alphabetize: {
					caseInsensitive: true,
					order: 'asc',
				},
				'newlines-between': 'always',
			},
		],
		'one-var': ['error', 'never'],
		'no-var': 'error',
		'padding-line-between-statements': [
			'error',
			{
				blankLine: 'always',
				prev: '*',
				next: 'return',
			},
			{
				blankLine: 'always',
				prev: ['const', 'let', 'var'],
				next: '*',
			},
			{
				blankLine: 'any',
				prev: ['const', 'let', 'var'],
				next: ['const', 'let', 'var'],
			},
			{
				blankLine: 'always',
				prev: ['block', 'block-like', 'if'],
				next: '*',
			},
			{
				blankLine: 'always',
				prev: '*',
				next: ['block', 'block-like', 'if'],
			},
			{
				blankLine: 'any',
				prev: 'export',
				next: '*',
			},
			{
				blankLine: 'any',
				prev: '*',
				next: 'export',
			},
		],
		'@typescript-eslint/indent': 'off',
		'@typescript-eslint/prefer-interface': 'off',
		'@typescript-eslint/interface-name-prefix': 'off',
		'@typescript-eslint/ban-ts-comment': 'warn',
		'@typescript-eslint/explicit-function-return-type': 'error',
		'prefer-template': 'error',
	},
};
```

Any help would be appreciated with this!

**Comment by aMarCruz** [comment]
@bduff9 , please test the v0.17.0 (it is already in npm)
Sorry by the delay.
